### PR TITLE
Move to rdkafka library

### PR DESCRIPTION
**Pull request by lindgrenj6**
Updating the dependencies to use the librdkafka library in miq-messaging.

\# TODO: 
- [x] make sure this line works: https://github.com/lindgrenj6/sources-api/blob/ef3322d29881305af1d332ec0916287a2490cd0b/lib/sources/api/messaging.rb#L21

Depends on:
~- [ ] https://github.com/RedHatInsights/topological_inventory-core/pull/209~

### CODE REVIEW

**Comment by slemrmartin** [comment]
@lindgrenj6 is it ready to switch the gem version to 1.0.0?

**Comment by lindgrenj6** [comment]
@slemrmartin Yes I need to get this one updated and then validate the `TODO:` line in the description works still, it's the one place we use that method.

**Comment by lindgrenj6** [comment]
@slemrmartin @syncrou I think this is ready to go now (once the specs pass), we have a nice helper method for the topics piece! Thanks @bzwei!

**Comment by slemrmartin** [comment]
@lindgrenj6 specs didn't pass

**Comment by lindgrenj6** [comment]
@slemrmartin fixed, I didn't realize the mocks were wrong.

**Review by roliveri — APPROVED** [review]

**Review by slemrmartin — APPROVED** [review]

**Pull request merged**
