### PR TITLE
Provide list_operation_id to resolve duplicates

### PR DESCRIPTION
**Pull request by mkanoor**
https://projects.engineering.redhat.com/browse/TPINVTRY-923

The ApplicationAuthentication class was causing duplicate
operation ID to be generated

https://github.com/RedHatInsights/insights-api-common-rails/pull/182

### CODE REVIEW

**Comment by mkanoor** [comment]
The spec failure is due to the fact that status should be an string and not an integer

**Comment by gmcculloug** [comment]
@mkanoor Please rebase

**Comment by mkanoor** [comment]
@gmcculloug Waiting for the release of the insights-api-common in ruby gems
And also on this PR https://github.com/RedHatInsights/sources-api/pull/219

**Comment by gmcculloug** [comment]
@mkanoor New api-common is released.

**Comment by mkanoor** [comment]
@syncrou @gmcculloug 
Please review

**Pull request merged**
