### PR TITLE
Add openapi spec validation in travis

### PR DESCRIPTION
**Pull request by bzwei**
Apply the same change as RedHatInsights/approval-api#338

### CODE REVIEW

**Comment by bzwei** [comment]
The build failed because it successfully found the openapi error:
```
1155Validating spec (./public/doc/openapi-3-v1.0.json)
1156Warnings: 
1157	- Unused model: Tenant
1158
1159[info] Spec has 1 recommendation(s).
1160Validating spec (./public/doc/openapi-3-v2.0.json)
1161Errors:
1162	- attribute paths.'/applications/{id}/authentications'(get).operationId is repeated
1163
1164[error] Spec has 1 errors.
1165
```

**Comment by gmcculloug** [comment]
cc @mkanoor

**Comment by gmcculloug** [comment]
Cleared the approval as we should probably resolve this issue (PRs in progress) before we merge this.  See https://github.com/RedHatInsights/sources-api/pull/215

**Comment by mkanoor** [comment]
👍 It caught this error
```
Errors:
1162	- attribute paths.'/applications/{id}/authentications'(get).operationId is repeated
```

**Comment by mkanoor** [comment]
https://projects.engineering.redhat.com/browse/TPINVTRY-923

**Pull request merged**
