### PR TITLE
Revert "Pin insights-api-common to 5.0.2"

### PR DESCRIPTION
**Pull request by lindgrenj6**
This reverts commit 244b1ea4acd901144f305e5a20f0f8556544a1be.

### CODE REVIEW

**Comment by slemrmartin** [comment]
@lindgrenj6 is it ready to merge?

**Comment by lindgrenj6** [comment]
Yes, this was just something I initially tried due to the UTF-8 Error
in CI last week as it was the only thing that changed recently. 

#227 will probably fix it!

-- 
Jacob Lindgren

Senior Software Engineer - Insights Platform
Red Hat
***@***.***     M: 402-841-6173

**Comment by slemrmartin** [comment]
@lindgrenj6 #227 is closed in favor of #231, but it's closed too :)

**Comment by lindgrenj6** [comment]
@slemrmartin oop - https://github.com/RedHatInsights/insights-api-common-rails/pull/227

**Pull request merged**
