### PR TITLE
[RHCLOUD-17686] feature: "ROS" as an application type for the AWS source

### PR DESCRIPTION
**Pull request by MikelAlejoBR**
For now, they only support AWS, so we will leave Azure aside.

[RHCLOUD-17686](https://issues.redhat.com/browse/RHCLOUD-17686)

### CODE REVIEW

**Review by rvsia — APPROVED** [review]
Looks great! 🏆

**Comment by MikelAlejoBR** [comment]
Whoops, I broke sources. But it seems unrelated to my change? I reverted my commit, force-pushed, and still fails with a `Psych::DisallowedClass: Tried to load unspecified class: Time` error.

**Comment by lindgrenj6** [comment]
Definitely not you - the tests seem to have broken on sources for some reason.
I've been trying to fix it with the other PR checking in Gemfile.lock

-- 
Jacob Lindgren

Senior Software Engineer - Insights Platform
Red Hat
***@***.***     M: 402-841-6173

**Comment by MikelAlejoBR** [comment]
Thank you Jacob. Let me know if I can help.

**Review by lindgrenj6 — APPROVED** [review]

**Pull request merged**
