### PR TITLE
[WIP]Add after_destroy callback for App, Auth and Endpoint models

### PR DESCRIPTION
**Pull request by pkomanek**
Adding `after_destroy`callback for Authentication/Application/Endpoint with requesting a new `availability_status` check on related source.

Depends on https://github.com/RedHatInsights/sources-api/pull/316.
Based on https://github.com/RedHatInsights/sources-api/issues/317.

### CODE REVIEW

**Comment by pkomanek** [comment]
cc @lindgrenj6 @slemrmartin

**Comment by lindgrenj6** [comment]
Merged the master branch in via the UI to get the emails to stop.

**Comment by slemrmartin** [comment]
@pkomanek is it WIP or waiting for review?

**Comment by slemrmartin** [comment]
closing, will be replaced by a PR following to the #378

**Pull request closed without merging**
