### PR TITLE
Add an internal API to update the application_types

### PR DESCRIPTION
**Pull request by agrare**
Allow applications to update their application_type record over the
internal API

### CODE REVIEW

**Comment by agrare** [comment]
@abellotti @bdunne without the PATCH in the openapi spec the internal API update fails, but with it the specs fail on the missing route in the main API.

**Comment by Fryguy** [comment]
Note that if application type is externally modifiable, then you're going to need to change the way seed works (unless seed is *literally* first time ever)

**Comment by agrare** [comment]
Yeah we can't seed the url because the hostnames will be different based on what environment we're on (CI/QA/PROD)

**Comment by agrare** [comment]
Closing this in favor of pulling the hostname out of a config map.

**Pull request closed without merging**
