### PR TITLE
Add an availability check URL for applications

### PR DESCRIPTION
**Pull request by agrare**
Add a URL for applications to register to allow for per-app availability
checking of sources.

This will be invoked by the normal availabililty check (scheduled and
on-demand) for all enabled applications for a source.

Applications will receive a POST action to check the availability of all
related resources for the specified source by ID, then the application
will update the source via the API to set the availability_status.

### CODE REVIEW

**Comment by abellotti** [comment]
Hi @agrare this is fine.

How is this to be updated ? PATCH /application_types/{id} for apps to update their url or
something else, maybe a configmap loading in this info since this is more of a system
configuration setting.

**Comment by agrare** [comment]
@abellotti I was picturing a PR to update the application_type seed https://github.com/RedHatInsights/sources-api/blob/master/db/seeds/application_types.rb

**Comment by abellotti** [comment]
That works 👍 , though that means having to redeploy sources anytime another app type updates their app url, there may be other options.

**Comment by gtanzillo** [comment]
I wouldn't expect the URL to change very often. I would expect that to be tied to a change on the application side where there was a need to change the URL for some reason.

**Comment by agrare** [comment]
Yeah, this is the same process for everything that we seed.

**Pull request merged**
