### PR TITLE
[WIP] Prototype for storing encrypted columns in a vault

### PR DESCRIPTION
**Pull request by gtanzillo**
This is a prototype for using [Hashicorp vault](https://www.hashicorp.com/products/vault) for storing passwords instead of the DB.

ToDo:
- [ ] Tests
- [ ] Add support for vault namespace/engine, currently hardcoded to "secret"
- [ ] Migration of existing passwords
- [ ] Install and configure a vault. I'm testing this locally

### CODE REVIEW

**Comment by abellotti** [comment]
NICE!!  👍  Do we need to add support for namespaces, i.e. like vault kv get --namespace=xyzzy or via the VAULT_NAMESPACE environment variable ? or do we have enough for compartmentalizing the apps ?

**Comment by gtanzillo** [comment]
@abellotti Yes, we definitely need to handle namespaces. I'll add it to the todo list

**Comment by slemrmartin** [comment]
@syncrou close it?

**Comment by syncrou** [comment]
@slemrmartin, yeah, for now it makes sense. We can always reopen and/or use it as a reference for later if need be.

**Pull request closed without merging**
